base_url = "https://chemifiqrebi.online"
compile_sass = true
build_search_index = false
theme = "no-style-please"
title = "CHEMI FIQREBI ONLINE"
minify_html = true

[markdown]

[extra]
author = "Elene"
